version: '3.7'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.localhost`)"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: portainer_data
        target: /data
        volume:
          nocopy: true
    networks:
      - proxy

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=storage,rw,nolock,soft"
      device: ":/storage/volumes/admin/portainer/data"

networks:
  proxy:
    external: true
 